### Creates a new patient entity
POST https://careplus-api.up.railway.app/api/patient
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Yash4",
  "lastName": "Op3",
  "userId": "34567865",
  "email": "yashOpkjhikuh@example.com",
  "phoneNumber": "8850529588",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28",
  "privacyConsent": true
}

###