spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["http://localhost:3000", "https://careplusai.netlify.app"]
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # ----------------------- Auth Service -----------------------------------------------------------
        - id: auth-service-route
          uri: http://auth-service:7002
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # ----------------------- Patient Service -----------------------------------------------------------
        - id: patient-service-options
          uri: http://patient-service:7001
          predicates:
            - Path=/api/patient/**
            - Method=OPTIONS
          filters:
            - StripPrefix=1

        - id: patient-service-get
          uri: http://patient-service:7001
          predicates:
            - Path=/api/patient/**
            - Method=GET
          filters:
            - StripPrefix=1

        - id: patient-service-secured
          uri: http://patient-service:7001
          predicates:
            - Path=/api/patient/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
            - StripPrefix=1
            - JwtValidation
        # ----------------------- appointment Service -----------------------------------------------------------
        - id: appointment-service-options
          uri: http://appointment-service:7003
          predicates:
            - Path=/api/appointment/**
            - Method=OPTIONS
          filters:
            - StripPrefix=1

        - id: appointment-service-get
          uri: http://appointment-service:7003
          predicates:
            - Path=/api/appointment/**
            - Method=GET
          filters:
            - StripPrefix=1

        - id: appointment-service-secured
          uri: http://appointment-service:7003
          predicates:
            - Path=/api/appointment/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
            - StripPrefix=1
            - JwtValidation


server:
  port: 7070